/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup/route'
import { Route as LoginRouteImport } from './routes/login/route'
import { Route as TopicsTopicIdImport } from './routes/topics/$topicId'

// Create Virtual Routes

const MainLazyImport = createFileRoute('/main')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MainLazyRoute = MainLazyImport.update({
  path: '/main',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/main.lazy').then((d) => d.Route))

const SignupRouteRoute = SignupRouteImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRouteRoute = LoginRouteImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/route.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TopicsTopicIdRoute = TopicsTopicIdImport.update({
  path: '/topics/$topicId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      preLoaderRoute: typeof MainLazyImport
      parentRoute: typeof rootRoute
    }
    '/topics/$topicId': {
      preLoaderRoute: typeof TopicsTopicIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  LoginRouteRoute,
  SignupRouteRoute,
  MainLazyRoute,
  TopicsTopicIdRoute,
])

/* prettier-ignore-end */
